[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = false

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_commit]
tag_symbol = " tag "

[git_branch]
symbol = ""
format = "on [$branch]($style) "
style = "bold yellow"

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
style = "bold #D89216"

[aws]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[cmake]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[docker_context]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[golang]
disabled = true

[hg_branch]
disabled = true

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[nodejs]
symbol = ""
format = ""

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[purescript]
symbol = "purs "

[python]
symbol = ""
format = ""

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[swift]
symbol = "swift "
